//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IPSyncing.IPSyncServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IPSyncServiceReference.IIPSync")]
    public interface IIPSync {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPSync/Sync", ReplyAction="http://tempuri.org/IIPSync/SyncResponse")]
        string Sync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPSync/Sync", ReplyAction="http://tempuri.org/IIPSync/SyncResponse")]
        System.Threading.Tasks.Task<string> SyncAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPSync/DiscardPCIP", ReplyAction="http://tempuri.org/IIPSync/DiscardPCIPResponse")]
        bool DiscardPCIP(int user_id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIPSync/DiscardPCIP", ReplyAction="http://tempuri.org/IIPSync/DiscardPCIPResponse")]
        System.Threading.Tasks.Task<bool> DiscardPCIPAsync(int user_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIPSyncChannel : IPSyncing.IPSyncServiceReference.IIPSync, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IPSyncClient : System.ServiceModel.ClientBase<IPSyncing.IPSyncServiceReference.IIPSync>, IPSyncing.IPSyncServiceReference.IIPSync {
        
        public IPSyncClient() {
        }
        
        public IPSyncClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IPSyncClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IPSyncClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IPSyncClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Sync(string token) {
            return base.Channel.Sync(token);
        }
        
        public System.Threading.Tasks.Task<string> SyncAsync(string token) {
            return base.Channel.SyncAsync(token);
        }
        
        public bool DiscardPCIP(int user_id) {
            return base.Channel.DiscardPCIP(user_id);
        }
        
        public System.Threading.Tasks.Task<bool> DiscardPCIPAsync(int user_id) {
            return base.Channel.DiscardPCIPAsync(user_id);
        }
    }
}
